### ISSUE TITLE
Where is WPELauncher?

### ISSUE THREAD

**Issue by wuhanck** [WebPlatformForEmbedded/WPEWebKit#262]
I am using ubuntu 16.04.
I follow the guide and find that there is no WPELauncher.
Do I miss something or how can I build "WPELauncher"?

**Comment by maruku** [comment]
https://github.com/WebPlatformForEmbedded/WPEWebKitLauncher

**Comment by wuhanck** [comment]
@maruku 
I know there is a WPEWebKitLauncher.
But there is no guide how to build it.
Simple "clone; cmkae .; make" does not work.
How can I build "WPELauncher"?

**Comment by maruku** [comment]
How do you build WPE? using buildroot or yocto? 
You may ref to https://github.com/WebPlatformForEmbedded/buildroot if you are using buildroot. 
(https://github.com/WebPlatformForEmbedded/buildroot/tree/master/package/wpe/wpelauncher)

**Comment by wuhanck** [comment]
@maruku 
Thank you for your help.
At current stage, I need to run it under ubuntu 16.04....
Or I want to go through the README of WPEWebkit.
I will dig the info. Thx.

**Comment by maruku** [comment]
Hi @wuhanck 
I build wpe and wpelauncher using ubuntu 16.04, too. but we use crosscompile and generate images for custom ARM hw). Good luck.

**Comment by hjongman** [comment]
I have the same issue here.

I followed the instruction at https://github.com/WebPlatformForEmbedded/WPEWebKit.

When I try ./Tools/Scripts/run-wpe command, it gives following error;

$ ./Tools/Scripts/run-wpe
Can't find /usr/src/WPEWebKit/WebKitBuild/Release/bin/WPELauncher at ./Tools/Scripts/run-wpe line 52.

Maybe the instruction of above webpage needs to be updated, because WPELauncher is not built by default ?

I'd like to know how I can build the WPELauncher.
Like wuhanck, I'm using Ubuntu 16.04.2 LTS x86_64, and not cross-compile.

I'd like to build the WPE and run it on x86 first.

**Comment by propella** [comment]
I had the same issue, but it seems that WPELauncher has been disabled intentionally...

https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/932cd9a91b8ad99adb1af8976e2adbd5035ab390#diff-ba631b96e9ee762728519732db719855R41

**Comment by rdpascua** [comment]
I'm having the same issue as well. cd16f60 gives me the same error you are having

**Comment by emirotin** [comment]
Same here, Linux MInt 18 (same Ubuntu 16), followed the build procedure from the readme, same error

**Comment by albertd** [comment]
Closing thread as it's very out-dated
