### ISSUE TITLE
Response time is slow when we press OK key in Youtube/tv content.

### ISSUE THREAD

**Issue by nambirajang** [WebPlatformForEmbedded/WPEWebKit#269]
We are seeing ~3sec delay when we press OK key in Youtube/tv content in Pace XI3 device.
KeyPress event is processed immediately but It takes 2 sec for KeyUp event to reach WebPage::keyEvent() API. After that HTML MediaElement Creation and Gstreamer pipeline starts.

This delay got reduced to ~2sec when we change the optimization flags from Os to O2/O3.

**Comment by nambirajang** [comment]
We used KeyEvent_time.patch for time analysis in WebPage::keyEvent() API.
Please check, https://gist.github.com/emutavchi/e0df5bbc0298b34061ced28d46a15873

Attached the 'OK-Response-with-OptimizationFlags' file for output of KeyEvent_time.patch.

[
[OK-Response-with-OptimizationFlags.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/992991/OK-Response-with-OptimizationFlags.txt)
](url)

**Comment by wouterlucas** [comment]
It seems to be a race between the video and rendering thread fighting over the CPU, where the rendering thread is not getting any resources because the video pipeline is being set up. 

If you change the priority of the render thread it will improve the UX:
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/master/Source/WebCore/platform/graphics/texmap/TextureMapperPlatformLayerProxy.cpp#L51

Change that to 40 and let me know how that works for you. When I run this on a 7429 single core MIPS device it is a lot better, UI continues to the next screen and a least the user gets feedback that YouTube is busy on starting the video playback.

This wont be an issue on more powerful devices, especially those with HT or multi cores. 

Additionally if the device has been released prior to 2013, you can request YouTube for a version with less animations to ease the device a little. This can be toggled using the user-agent and should help a lot on your older MIPS devices.

**Comment by nambirajang** [comment]
Hi Wouter,
We have increased the priority as per your suggestion in both Os and O2. 
Still the same delay is observed.

**Comment by wouterlucas** [comment]
OK, that's unfortunate looked like a quick workaround until we can optimize -Os build in general. It does seem to matter a little bit on the reference MIPS device I have over here.

We'll have to take a deeper look at the -Os build and we'll update you guys on the progress.

**Comment by wouterlucas** [comment]
For the size, the latest comment from Zan should reduce the MIPS size from 40 to 36MB:
https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/2ae50124fc319fbe19124af115902febc18b2d08

Please confirm if that's enough to get you within the size limitations on the device to switch to -O2 entirely.

Additionally with the latest stable we're not seeing the 7 to 8s delay anymore on -Os. Tested on a both rpi0 and a reference MIPS device we're seeing <3s on -Os and <2s on -O2. Please confirm if you see the same with latest stable.

**Comment by ssharma-rdk** [comment]
Hi Wouter,

All our builds are using -O2 and we still see up to 2 second delay in processing OK key. Could this be related to JSC performance?

**Comment by guijemont** [comment]
I spent some time looking at the js performances in that specific scenario.
First, I made a patch to run JSC's sampling profiler in the lapsus of time that your are measuring in WebPage::keyEvent, and ran that on my MIPS device, on which the total time span for this part of keyEvent() is usually at a bout 1-1.5s (depending on how much instrumentalisation I put on it)
Here are the top js functions seen to be taking time:
```
Sampling rate: 1000 microseconds
Hottest bytecodes as <numSamples   'functionName#hash:JITType:bytecodeIndex'>
    72    'focus#<nil>:None:<nil>'
    66    'setAttribute#<nil>:None:<nil>'
    48    'resolve#<nil>:None:0'
    23    '#<nil>:None:0'
    18    'bound #<nil>:None:<nil>'
    14    '#<nil>:None:24'
    12    '#<nil>:None:<nil>'
    11    'Xm#<nil>:None:322'
    10    'A#<nil>:None:101'
    10    '$m#<nil>:None:837'
```
I also ran a similar profiling on chromium on my x86_64 laptop. There are three methods that appear to differ in the results (appear near the top on jsc/mips but not on): `focus()`, `setAttribute()` and `bound ()`. `bound ()` (note the space) seems to be actually many different functions for which we fail to get the name (just like `#<nil>`, none of which seems to take a lot of time individually.

`focus()` and `setAttribute()` are both DOM functions. I did a different instrumentation to measure the time spent in DOM functions, by measuring the time taken by `callOperation()` in JSDOMBinding.h, and grouping it by DOM function. Here is the full result:
```
keyEvent processing time: 1119 ms
DOM function     Time spent (ms)
focus   85.9189
setAttribute    67.0003
add     5.42714
item    3.62359
requestAnimationFrame   3.43085
cloneNode       3.06822
createEvent     2.96044
querySelector   2.4374
send    2.02478
remove  1.90867
replaceChild    1.55652
createElement   1.08537
open    0.750075
initEvent       0.629853
removeChild     0.435705
setTimeout      0.199148
appendChild     0.155298
insertBefore    0.150334
now     0.104963
getItem 0.038333
setRequestHeader        0.037741
clearTimeout    0.007222
stopPropagation 0.002926
preventDefault  0.002703
Total for DOM funcitons (ms): 182.957
```
As you can see, this matches the results of the sampling profiler, but we're still looking at a relatively small part of the time spent on that function.

Indeed, if we look at the sampling profiler results, since it takes one measurement per ms, for the functions that have a higher hit rate, we can approximate the number of hits to a number of ms. This means that we're not looking at anything that takes a huge amount of time, neither in JS code execution nor in DOM function implementations.
It could be that the sampling profiler fails to identify some things as js execution (I did not study its implementation, so I don't know), but so far that's the way it looks.
In any case, the next step should be to try to measure things with a generic c/c++ profiler to see if we can identify what takes time.
There is also another function that I left out: `resolve()` seems to be part of the youtubeTV code base, and does take significantly more percentage of total time on WPE/Mips than on chromium, though even if we could fix that, we're only looking at about 5% of execution time.
