### ISSUE TITLE
Accelerated compositing bug: rendering issues when using <video> and backface-visibility

### ISSUE THREAD

**Issue by igor-borovkov** [WebPlatformForEmbedded/WPEWebKit#310]
Original ticket: https://ccp.sys.comcast.net/browse/WKIT-973

Multiple rendering issues caused by using "video" tag on a page, position:fixed, and -webkit-backface-visibility: hidden. 

Workaround: disable accelerated compositing for a "video" tag

Example for a specific rendering issue among many others: "border-radius" stops working
```html
<!--BUG: the image doesn't have rounded corners although border-radius property specified-->

<body style="background-color: #E3E5EB;">

	<div style="position: fixed">
		<!-- IGOR: won't be reproducible unless position is fixed-->

		<video >	
		<source src="bla">
		<!-- IGOR: source and src should be specified, doesn't matter which media player is getting created; 
		 all of them trigger accelerated compositing layer -->
		 
		</video>
	</div>

	<!--IGOR: not reproducible unless -webkit-backface-visibility is specified -->
	<img  style="border-radius: 12px; -webkit-backface-visibility: hidden;" src="you can use any image here" >

</body>
```

**Comment by igor-borovkov** [comment]
there are 2 out of 3 rendering issues that are still reproducible after #311 temporary fix. Both are not related to a border radius: a position issues, and a visibility issue. Both are related to a presence of <video> on a page.

**Comment by magomez** [comment]
@igor-borovkov, I'm going to need concrete examples of the rendering issues you're having so I can work on them. If you could create some small tests that would be awesome. If not, I'm going to need access somehow to your app (not sure if it's possible).

In the meanwhile I can give you some advice: backface-visibility doesn't guarantee the creation of a compositing layer. I suspect you're using it to accelerate animations, but it only guarantees the creation of a layer when it's inside a preserve-3d container. In the example you put in #311, for example, the image was pushed to a layer just because the previous div was empty (and this caused the div and the image to overlap). If you put an element inside the div then the image wouldn't be in a new layer. I haven't tested this example, but I'm pretty sure the image is pushed to a new layer because of the fixed position of the video. You could remove backface-visibility in both examples. Actually, before the patch for #311, you could easily reproduce the problem just with
`<body>
<img  style="border-radius: 12px; -webkit-transform: translate3D(0,0,0);" src="image" >
</body>`
 because translate3D doesn guarantee the creation of a new layer.

**Comment by albertd** [comment]
@igor-borovkov please reopen if still valid.
