### ISSUE TITLE
While scrolling text in a div, artifacts of previous line of text are left behind.

### ISSUE THREAD

**Issue by vanihegde** [WebPlatformForEmbedded/WPEWebKit#363]
This issue was seen on one of the html based applications.
Since the original application code is complicated, I have tried to reduce it to as minimal as I could.
[testPage.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1258237/testPage.zip)

Original issue: https://ccp.sys.comcast.net/browse/XRE-11783
Original app page for which issue was reported: https://channelstorex1.xidio.net/channelstore-webapp/channelstore/#watch/publisher/1438/show/13871/video/36067

Any of the below modifications in the style sheet eliminate the issue:
1) Removing  `box-sizing: border-box` from `button` class
2) Reducing the `font-size` in `.subscription-container .subscription-terms`
3) Increasing the `line-height` in `.subscription-container .subscription-terms`

![leftoverartifacts](https://user-images.githubusercontent.com/2871718/29791551-4bc55da2-8c0b-11e7-94f4-c771e7e2a597.png)

Note: The issue is not seen with Qt WebKit.

**Comment by magomez** [comment]
I've been looking into this for a while. At first I thought it was a font problem, and tried with different versions of freetype and harfbuzz but the issue was there anyway. After some debugging I found that the artifacts show up when part of the text inside subscription-terms is drawn inside the 2 superior tiles of the page, as if when redrawing those they didn't realize that the content in subscription-terms has been scrolled. All the methods described to avoid the issue have the effect of avoiding the text to be shown inside the 2 superior tiles, and that's why the artifacts are gone. I'll keep investigating.

**Comment by magomez** [comment]
I've just pushed da8849fa8654302b55d2f678685a5b8314ec6565 which fixes the problem. Can you test it  @vanihegde, and close the issue if it works for you?

**Comment by magomez** [comment]
I thought of a more efficient fix instead of the one I committed, so I reverted it and added 42b65f9477d40e6b0c558229e4dd63112eaddc06 as the fix instead. Please test this one @vanihegde.

Thanks!!

**Comment by vanihegde** [comment]
@magomez Sorry for the delay in response. Yes your commit fixes the issue. Thanks!

**Comment by vanihegde** [comment]
BTW, can you please merge this to stable?

**Comment by wouterlucas** [comment]
Yep, we'll add it to stable asap.
