### ISSUE TITLE
WTFCrash in JavaScriptCore during Youtube video playback

### ISSUE THREAD

**Issue by nrajan002c** [WebPlatformForEmbedded/WPEWebKit#405]
Hi @guijemont,
We are observing WTFCrash in JSC during youtube video playback in 5c0c3fd wpe stable version.
Issue is seen in ARM & Mips platforms and we used O2 optimization flag in wpe compilation.
[WTFCrash-1.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1467614/WTFCrash-1.txt)
[WTFCrash-2.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1467615/WTFCrash-2.txt)
[WTFCrash-3.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1467616/WTFCrash-3.txt)

**Comment by guijemont** [comment]
Are you using the sampling profiler when this happens (from the web inspector)?

**Comment by nambirajang** [comment]
Steps to reproduce:
1. Start Youtube video playback.
2. Leave it for long run.

**Comment by aazamansari** [comment]
I think this crash is same /similar to https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/327

**Comment by aazamansari** [comment]
We are still observing this crash with the latest JavaScriptCore fixes.

**Comment by aazamansari** [comment]
For the JavaScriptCore crash we are observing, based on the stacktrace it looks like from one thread we are releasing the resource and form another thread we are trying to access the same resource which is causing major of the crashes

I think we should have some kind of locks while releasing and accessing/using the resource to avoid these crashes.

In our case since we set the memory limit to 150MB we do see MemoryPressureHandler calling GC more frequently when memory usage reaches >150MB

**Comment by guijemont** [comment]
Update on my attempts to reproduce: I had a bunch of crashes, but that looked unrelated and due to the graphics drivers of my device. I updated said drivers and launched some long time youtube playback again. That was a few hours ago, I will see if the crash reproduces over the week end.
Alternatively, if someone who can reproduce easily can provide a core file + build files, that would be welcome as well, as it's hard to conclude anything from the backtraces alone.

**Comment by guijemont** [comment]
@aazamansari Is that a crash that you are still able to reproduce? We have a patch for an issue that might be the same as yours that could be interesting to try.

**Comment by nrajan002c** [comment]
Hi @guijemont ,
This issue is still reproducible in our STB. Could you please share the patch. 
We can try it out.

**Comment by guijemont** [comment]
@nambirajang I've backported a [patch that might fix it](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/40dbe1683f43a1378356aaa08a4b6deea7e82e1e). Please test with itand let me know if the issue still reproduces.

Also please note that this is not the permanent fix that will land upstream, and it could potentially have some side effects, so it would require extensive testing before using it in production.
For more details see the [upstream issue](https://bugs.webkit.org/show_bug.cgi?id=197797)

**Comment by nrajan002c** [comment]
Thanks @guijemont . I will apply this patch and update you the result.

**Comment by nrajan002c** [comment]
Hi @guijemont ,
JSC crash is still observed with the fix. 
We are using "c0bb44a4053c261212b865e74b553816d88a9d37" revision in wpe-20170728 branch.
I have attached the minidump stack trace. can you please check it.
[crash.docx](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/3631598/crash.docx)

Thanks.

**Comment by guijemont** [comment]
I believe this has a high chance of being fixed by 80c28477227cd600a416a1caa7c45ba3cb800d72. If you are still able to reproduce the issue, can you check whether this fixes it? (I expect the patch should be trivial to apply on wpe-20170728 )

**Comment by guijemont** [comment]
Patch has been backported to the wpe-20170728 branch, let me know if this looks like it fixes the issue for you.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
