### ISSUE TITLE
how to enable texture mapper into wpewebkit

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#414]
Hi,

In default configuration it seems Texture mapper is not enabled. Is there anyway/flag to make Texture mapper enabled for Wpewebkit?

**Comment by magomez** [comment]
TextureMapper is enabled by default in Source/cmake/OptionsWPE.cmake:

SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER TRUE)
SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER_GL TRUE)

And I haven't found any user that is building with those options disabled, as it's not supported, unless you implement you own graphics path for that option. If TextureMapper is disabled for you it's probably because you have disabled it somehow. Where are you getting the code from? Are you applying custom patches? How are you building?

**Comment by karora123** [comment]
yes, I observed through this way, seems like FPS calculator, part of Texture Mapper is not displayed even after setting WEBKIT_SHOW_FPS to 1. For reference, I have created WPE Yocto image for RPI using instruction "https://github.com/WebPlatformForEmbedded/meta-wpe".
