### ISSUE TITLE
No sdcard.img generation in buildroot anymore

### ISSUE THREAD

**Issue by T94T** [WebPlatformForEmbedded/WPEWebKit#500]
Hi,
I'm using the raspberrypi0_wpe_defconfig. With the latest version there is no sdcard.img generation anymore.
When comparing with the raspberrypi3_wpe_defconfig there are lots of differences. It seems the 3 defconfig is still generating the sdcard image.
Why is that so?

**Comment by albertd** [comment]
Everything is now in a zImage (Ramdisk) and everything just needs to be placed in the fat32 partition, the ext4 is used for cache.

**Comment by T94T** [comment]
I'm still trying to get a working sd card but it's not booting. These are my steps I've done.

- SD card with a 500MB FAT32 partition (Primary, labeled with boot) and an ext4 empty partition
- Copied the ./images/ content to the boot partition
- Copied the ./images/rpi-firmware/ content to the boot partition

When booting up, the activity LED on the RPi flashes for a while. HDMI screen info shows the "raspberry" host name but it keeps black.

Can you please give me some hints to get this working?

**Comment by hlev** [comment]
@T94T which branch are you building off of?

**Comment by T94T** [comment]
Just with the current master branch.

**Comment by T94T** [comment]
`cmdline.txt` is
vt.global_cursor_default=0 root=/dev/mmcblk0p2 rootwait console=ttyAMA0,115200 quiet

`config.txt` is
https://pastebin.com/maXcULe6

`inittab` is
https://pastebin.com/yv83C0a2

Thank you for your help!

**Comment by T94T** [comment]
>  when the display shows hostname
Just to be clear: The hostname is only displayed as an OSD information when connected to a TV over HDMI. The Raspberry pi output is black right from the time on which it is powered on.

**Comment by hlev** [comment]
I suggest first you change `cmdline.txt`:
```
vt.global_cursor_default=0 root=/dev/mmcblk0p2 rootwait console=tty1
```
This way you would see kernel log messages on HDMI, and at least know that the bootloader can load the kernel. I guess you don't use the serial console, so you can remove the `ttyAMA0,115200` entry. Make sure you remove `quiet` as well, because it suppresses most kernel messages.

The `root=` and `rootwait` entries are suspicious as well and I think contradict what @albertd says, if everything is in the `zImage` then these params should not be there. Let's see what happens and go from there.

The current `inittab` in `master` only puts a login terminal on the serial console (as in your pastebin)
If you need a login terminal on HDMI, change your `inittab` as well.

```
tty1::respawn:/sbin/getty -L tty1
```
For a quick&dirty solution, you can make this `inittab` change in your `/output/target` directory and run `make` again to build a new `zImage`, or extract, change and repack your `zImage` manually. For a better solution, you could patch `post-build.sh` to add the login terminal on `tty1`, or override the path of the post-build script in buildroot configuration to your own script.

**Comment by T94T** [comment]
I just made all suggested adaptions. It seems the raspberry boots ok. Activity LED is off during this process - strange.
I attached a keyboard but I cannot get a login prompt. See picture attached.
![bootmessages](https://user-images.githubusercontent.com/17198363/47085229-4bf10400-d216-11e8-99f8-d6d46f6f1ee8.png)

WIFI is also not working. WIFI is working on all other bare buildroot systems I made though...

**Comment by hlev** [comment]
Did you remove the `root=` and `rootwait` kernel parameters then?
Do you have `/output/target/root` and `output/target/boot`? Those mounts failing suggest there're no `/root` and `/boot` dirs in the initramfs.
Do you get a login prompt by any chance if you press Enter?

If not then it seems  your `inittab` changes don't persist. Did you do a complete rebuild, by any chance? You should only make changes to the already built target and then run `make` again to only build the `zImage` from there.

If you clean everything and start over, you can as well set BR2_TARGET_GENERIC_GETTY in the defconfig for a login TTY on tty1.
`make menuconfig` > System configuration > Run a getty after boot, set it to `tty1`.

**Comment by T94T** [comment]
> Did you remove the root= and rootwait kernel parameters then?

Yes

> Do you have /output/target/root and output/target/boot?

Yes, they are there

> Do you get a login prompt by any chance if you press Enter?

No

> If not then it seems your inittab changes don't persist.

Same thing came into my mind also. But I did not get managed the zImage repacking.

> BR2_TARGET_GENERIC_GETTY

This package is already activated.

I will try to recompile the whole thing tonight.

**Comment by T94T** [comment]
Another question: What I have to do so I have the sdcard.img again?

**Comment by hlev** [comment]
Look at the [post-image.sh](https://github.com/WebPlatformForEmbedded/buildroot/blob/2bb74d5213f3241b0abff544bccb72ba74842762/board/raspberrypi/post-image.sh#L194) script, that's where `genimage` is being run to generate an `sdcard.img` at the end of the build.
The image is created only if `BR2_TARGET_ROOTFS_EXT2_4 = y`. This can be set in "Filesystem images" in menuconfig. You can freely change the post-image script to generate any sdcard.img of your own with `genimage`, check https://github.com/pengutronix/genimages for the detailed docs.

Be aware that simply generating the image again with an ext4 rootfs on mmcblk0p2 will not instantly make this work. You would have to disable BR2_TARGET_ROOTFS_INITRAMFS as well, keep the `root=` and `rootwait` stuff in `cmdline.txt` and maybe it will work as you intended. But your best bet is always to go and look at the history of changes in defconfig, the board related files and the kernel configuration to figure out what has changed and what you may need to adjust or revert for your build.

What are you building that needs this extensive experimenting with `master` btw?

**Comment by T94T** [comment]
Thank you for your detailed explanations! We are going to invest some more time on this.

We need a hardware accelerated web browser. We tested the QT5 implementation as well as this WPEWebKit fork. The WPE browser works much faster and better. We are trying different approaches and we are experimenting with up to date versions preferably. Our goal is to have the official buildroot with WPE on top of it.

**Comment by hlev** [comment]
You're welcome. We use it in our product as well and I opted for the `stable` branch. Unless you need specific niche features that don't work, I'd think it would be as good as `master`.

I applaud the WPE people for opensourcing this, but there's not a lot of direction for which branch to work with and where it is heading. Or, equally possible, I'm just not well-versed enough to follow a large scale WebKit fork.

**Comment by hlev** [comment]
Thanks @wouterlucas, this definitely helps. I should have been more specific, when I meant `stable` I thought of `buildroot:stable`, since this thread is really about buildroot.

How do these releases of WPEWebKit correspond to the buildroot fork? For example, `buildroot:stable` uses 2a77c36869aa96766bf823d95852a4d49b0fd81a in `wpewebkit.mk` which is a commit from Jan 2018, so really cannot be that behind. Is it?

**Comment by wouterlucas** [comment]
I realized that after I sent my comment, sorry we've very WPE WebKit centric hence I assume its about that. The stable branch of this buildroot indeed points to wpe-20161117. 

The current master of this BR points to both wpe-20170728 and there is a dev option that allows you to build wpe-2.22. Though I won't recommend doing the latter as that would definitely put you on the edge of where a lot of stuff can go wrong. 

We do need to syncup this BR with upstream, but I don't know how or when we're going to do that. For example wpe-2.22 requires GST 1.14.2, which would be a reason to start bumping a bunch of packages.

**Comment by hlev** [comment]
I see. I've been trying to keep up by using `stable` as a baseline and manually bump the wpe family of packages to newer commits and try settle at a state where it works reliably. Knowing the above branching strategy will help with that a lot. I will have to diff and figure out what else than a newer WPEWebkit `buildroot:master` contains compared to `buildroot:stable` and we may be able to switch to `master` altogether.

**Comment by wouterlucas** [comment]
Yeah there are certainly a bunch of Gstreamer 1.10 patches that help a lot on master, but only makes sense if your actually doing media playback. Graphics wise the wpe-20170728 is just a bit faster, especially if you have more then 1 core on your device that you can utilize with the threaded compositing. 

The biggest difference is the deprecation of WPELauncher and transition into WPEFramework. Though with a little configuration they can be used to do the same. Flip side of that is WPEFramework can do a lot more then the simple WPELauncher ever did. I wrote a small intro on that over at the meta-wpe side: https://github.com/WebPlatformForEmbedded/meta-wpe/wiki/WPEFramework in case you want to dive down that route.

**Comment by hlev** [comment]
Absolutely! I shied away from WPEFramework when I started off, but I think I could give it a go now. Thanks for the pointers!

**Comment by hlev** [comment]
@T94T last night I built from `buildroot:master` for an rpi3, using [raspberrypi3_wpe_defconfig](https://github.com/WebPlatformForEmbedded/buildroot/blob/d4fe6b11b8b1b705204b883279b71425b7f50eb3/configs/raspberrypi3_wpe_defconfig) and ran into the same issues myself.

I think the problems stem from a couple of buildroot configuration settings and init scripts that may have gotten mucked up in `master`. Before we dive in again, let's try with a root shell in place of `init` first, so you can browse the files on your rpi0 rootfs at least. Use the `zImage` with the built-in initramfs.

```
// cmdline.txt
vt.global_cursor_default=0 console=tty1 rdinit=/bin/sh
```
This should give you a root shell and you can also compare your `output/target` directory with the actual running rootfs.

The issues I bumped into:

1. This may not affect you, but `master` did not manage to build `host-localedef` due to a deprecated header. I had to apply the patch from mainline buildroot. https://github.com/buildroot/buildroot/tree/master/package/localedef
2. The generated `cmdline.txt` is not in-line with the notion of rootfs being built into `zImage` I think the `root=` and `rootwait` parameters should not be there. We covered this already.
3. BR2_TARGET_GENERIC_NETWORK was not set in the generated defconfig, so networking configuration `/etc/network/interfaces` and the related init script `S40network` was not generated into the rootfs. However, the init script for dropbear `S50dropbear` is generated, and attempted to be started by `rcS`. Dropbear (SSH) would have little to no point without network, still, this may be intentional, so just make sure you address networking before you build by setting this config value and as well which interface should be configured DHCP by setting BR2_SYSTEM_DHCP, for example "eth0". Alternatively, you can put in place your own `/etc/network/interfaces` file and init script.
4. Mounts. For me, this was the main culprit. The order of mounting is still a bit messy in the generated rootfs on the rpi with busybox. Changes in the [rpi-firmware](https://github.com/WebPlatformForEmbedded/buildroot/tree/master/package/rpi-firmware) package resulted in the version of `S30mountroot` be copied to rootfs that wants to mount partitions from mmcblk**1** instead of mmcblk**0** and would loop&wait in the init script indefinitely. See `/etc/init.d/S30mountroot` on your system to validate this.

**Quick fix**

1. Check and change instances of `mmcblk1` to `mmcblk0` in `/output/target/etc/init.d/S30mountroot`
2. I suggest you as well change your `fstab` in `/output/target/etc/fstab`
```
# <file system>	<mount pt>	<type>	<options>	<dump>	<pass>
#/dev/root	/		ext2	rw,noauto	0	1
proc		/proc		proc	defaults	0	0
devpts		/dev/pts	devpts	defaults,gid=5,mode=620	0	0
tmpfs		/dev/shm	tmpfs	mode=0777	0	0
tmpfs		/tmp		tmpfs	mode=1777	0	0
tmpfs		/run		tmpfs	mode=0755,nosuid,nodev	0	0
sysfs		/sys		sysfs	defaults	0	0
 /dev/mmcblk0p1 /boot vfat noauto,ro 0 0
 /dev/mmcblk0p2 /data ext4 noauto,noatime,discard 0 
```
The changes here are:
- commented out the entry for `/` because `inittab` alreadt remounts `/` read-write.
- changed the SD card partitions to `noauto`, so the `mount -a` in `inittab` and elsewhere will not attempt to mount them. The device nodes `dev/mmcblk*` are not available yet when `mount -a` is being run for the first time from `inittab` so they would fail. They would be attempted to be mounted by `S30mountroot` again with `mount -a`, which would not work with this change, so you have to specify the partitions in the script explicitly. If you're OK with the error on the console, then just ignore this part, leave these on auto and they will be mounted eventually.
3. I disabled the unnecessary (i2c, 1Wire, etc) overlays in `config.txt` that I knew I would not need and to make sure neither hinders booting either. Initially I disabled all of them for, you may need to play around with them for working wifi.
4. Remove the `rdinit=` entry from cmdline.txt to resume the normal boot process.

I managed to get to the WPE splash screen this way. If you need a login prompt intead, you could disable the `S40WPEFramework` init script and have the `getty` line in `inittab` we already discussed. 

Hint: I don't know whether you use them already, but instead of changing things in `output/target`, on the long run, it's better to customize the rootfs with [overlays] (https://buildroot.org/downloads/manual/manual.html#rootfs-custom)

Hope this helps.

**Comment by T94T** [comment]
Wow, thank you @hlev !! I will dive into this today again.

**Comment by T94T** [comment]
Just finished making a full rebuild again. 
The `/etc/init.d/S30mountroot` already contained the right `mmcblk0` partitions. I hadn't to change anything. The `fstab` file and everything else I changed according to your suggestions. But it's still booting the same way as already mentioned. https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/500#issuecomment-430698997
I need to have a deeper look next week.
Thanks again for you great support!

**Comment by wouterlucas** [comment]
Hi @hlev just to shine a little light on:

```
BR2_TARGET_GENERIC_NETWORK was not set in the generated defconfig, so networking configuration /etc/network/interfaces and the related init script S40network was not generated into the rootfs. However, the init script for dropbear S50dropbear is generated, and attempted to be started by rcS. Dropbear (SSH) would have little to no point without network, still, this may be intentional, so just make sure you address networking before you build by setting this config value and as well which interface should be configured DHCP by setting BR2_SYSTEM_DHCP, for example "eth0". Alternatively, you can put in place your own /etc/network/interfaces file and init script.
```

This is done because the network will actually be brought up by WPEFramework in this case (which you can disable). The NetworkControl plugin will issue a DHCP request (or set a static) to bring up the network. See https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins/tree/master/NetworkControl for more details on the implementation.

Reason for stepping away from the init script is being able to launch WPE WebKit as early as possible, even when the system has no network, no time or things like that. That allows us to render graphics really early in the bootup process (~15s) and listen to the websocket connection on WPEFramework to figure out of the network has been set by NetworkControl, once we have network, location and time we can launch the final application. 

We all started this because staring at a fairly static boot screen for ~30s is just not needed anymore, idea is to get the WebKit up as early as possible and provide a more interactive experience as the rest of the system goes trough the remaining boot steps.

**Comment by hlev** [comment]
@wouterlucas thanks for the explanation, that makes sense. In fact in the image I had built based on `stable` I implemented just about the same mitigations, but with the traditional init scripts and utils, `ifupd`, etc. It will be much easier with WPEFramework!

All in all, my suspicion is still that in @T94T's case a script blocks and the boot process never reaches the `getty` line to put a TTY on tty1. Hence no login. In my case, the `while [ ! -e /dev/mmcblk1p1 ]; do sleep 1; done` was fairly obvious. I'm out of ideas off the top of my head, but will try an rpi0 build as well to see where it goes sideways.

@T94T I'm sorry that things still didn't work out. I'd say best is to go with `rdinit=/bin/sh` and try run the commands in inittab and the init scripts by hand to see where they trip up.

**Comment by MaximMikulich** [comment]
@hlev After the build, I got the folders, how to build cdcard.img? what commands use?

**Comment by hlev** [comment]
@MaximMikulich Usually the `post-image` script runs `genimage` to generate the image file. Here's an example: https://github.com/WebPlatformForEmbedded/buildroot/blob/b6ac25088962d0ced3a368ae720bfa3e05f1ebe0/board/raspberrypi/post-image.sh#L150

There is a corresponding `genimage.cfg` file in the board directory in buildroot which tells `genimage` what filesystems to create in the image and which files to copy over from the target or images directories (i.e. buildroot's output).

If you want a rootfs not bundled with the `zImage` you will have to make a couple changes to the current `buildroot:master` defconfig as well, but if you're OK with a bundled initramfs, then just copy the `zImage` to a FAT partition along with the firmware, config files and overlays.

Have a look at the https://github.com/pengutronix/genimage repo for details on how to create a `genimage.cfg` for various filesystem types and partition layouts in the image.

**Comment by MaximMikulich** [comment]
@hlev Did I understand correctly that I need to copy folders and files from "images" or "target" and from "rpi-firmware" to a USB flash drive?

**Comment by hlev** [comment]
@MaximMikulich Yes if you want to generate an SD card image for the current `master` build, then only files in the `images/` and `images/rpi-firmware/` directories matter. These go to a FAT partition.
If I remember correctly, on an RPi3, the current initramfs tries to mount the second, ext4 partition at `/root`, so you should configure an empty ext4 partition as well.

If you want to boot from USB and not SD, I think you can dump the generated image on a USB flash drive as well and it should work, however you need to setup your board for USB boot beforehand https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

**Comment by MaximMikulich** [comment]
@hlev I have black window....if use this
`vt.global_cursor_default=0 root=/dev/mmcblk0p2 rootwait console=ttyAMA0,115200 quiet`
if use this
`vt.global_cursor_default=0 console=tty1 rdinit=/bin/sh`
I see green led off...and on window more connections (ex: keyboard, mouse)...
but I don't run WPE browser....why?) sorry if I answer this question...

**Comment by MaximMikulich** [comment]
@hlev Before with sdcard.img it was easier .... as now I can not understand ...

**Comment by hlev** [comment]
@MaximMikulich 
It is beacuse with `rdinit=/bin/sh` you override the normal init process and you get straight into a root shell after boot. This is why the WPE browser doesn't run automatically.

If you use this instead:
```
vt.global_cursor_default=0 console=tty1
```
You will see the kernel log output during boot, the normal init procedure will run and the browser should start as well.

@albertd, @wouterlucas would you accept a PR that fixes the `root=` and `rootwait` parameters and optionally enables `sdcard.img` generation, or at least contains a helper script and a guide? It seems to trip people up.

**Comment by T94T** [comment]
Finally, this is what you have to do to generate a sdcard.img

**I got one problem though: It just boots the kernel and stops by saying "Waiting for root device /dev/mmcblk0p2"** Can not figure out what the problem is at the moment.

Run `make menuconfig` and make these changes.

1. Enable `dosfstools` and `mtools` under `Target packages > Filesystem and flash utilities
`
![filesystem config](https://user-images.githubusercontent.com/17198363/47950698-1a867100-df56-11e8-88a4-b0d30cb5e5e8.png)

2. Enable `ext2/3/4 root filesystem` under `Filesystem images` and choose `ext4` as `ext2/3/4 variant`. Also disable `initial RAM filesystem`
![filesystem images config](https://user-images.githubusercontent.com/17198363/47950701-2a05ba00-df56-11e8-81a9-e77f045c8179.png)

3. Enable `host genimage` under `Host utilities`
![host utilities config](https://user-images.githubusercontent.com/17198363/47950702-3558e580-df56-11e8-9bcb-e91dbda48474.png)

4. Edit the `board/raspberrypi/post-image.sh` and set the `GENIMAGE_CFG` to
 `GENIMAGE_CFG="${BOARD_DIR}/genimage-${BOARD_NAME}.cfg"`

5. Change `cmdline.txt`, so console output is visible on screen. Add `console=tty1` and remove `quiet`.

` vt.global_cursor_default=0 root=/dev/mmcblk0p2 rootwait console=tty1 console=ttyAMA0,115200`

**Comment by hlev** [comment]
@T94T just remove the `root=/dev/mmcblk0p2 rootwait` from `cmdline.txt`

**Comment by hlev** [comment]
@T94T Is the SD card initialized by the kernel, do you see `mmc` related entries in the log?

One thing I noticed with an initramfs setup is that the device nodes of `/dev/mmcblk0` are not created until `udev` is started. So with this non-initramfs approach, it may be that because of `rootwait`, the kernel waits for the device to appear indefinitely, because there's nothing to create the device node.

What setting do you have in "System configuration > /dev management"?

**Comment by T94T** [comment]
I do not see mmc related eintries because they are probably outside the screen. I have to test this with a serial port.
dev management is set to `Dynamic using devtmpfs + eudev`

**Comment by SamDecrock** [comment]
@T94T I followed your instructions to generate the sdcard.img and it worked!
It's showing me a nice "Hello" animation (which is suppose is WPE).

However, when I plug in a network cable, I get this:
![img_5231](https://user-images.githubusercontent.com/550487/48545303-e4d27800-e8c5-11e8-9a6e-c29dfd486d96.JPG)

Edit: despite the "something went wrong", I can go the the web interface running on the Pi and load the different test urls. This is cool :-)

**Comment by hlev** [comment]
@SamDecrock The error is simply the lack of configuration, you can ignore it.

I was interested in what actually goes wrong: https://github.com/WebPlatformForEmbedded/buildroot/blob/100355f78713cabf8b8b40db0f20580587653763/board/raspberrypi/index.html#L254

The page tries to load `config.json`, from the `/www` directory. Which if fails, yields this result.
The `post-build.sh` script would put this file in place if it existed in `/board/raspberrypi/`, it would copy the file along with `index.html` to `/www` on the rootfs. 

It seems to aid the configuration of the UX plugin with a default URL, per device. For example, given the following `config.json`:

```json
{ "ux": "devices/" }
```
After loading the file, the page makes another request to `devices/<device-id>` which it expects to be another JSON containing, for example:

```json
{ "url": "https://github.com" }
```
Then it configures the UX plugin with this URL.

If you SSH into your box and then create this structure, you can restart the WPE service and it will show "We're ready". Then, in the remote web interface, you'd see that the UX plugin is configured with the URL you specified. I don't know what else may or should be put in `config.json` or the device-specific config file.

```
/www/
|  index.html
|  config.json
|--devices/
    |   WPEuCfrvr0x  
```
Certainly, you can as well easily replace `index.html` with your custom landing page.

**Comment by SamDecrock** [comment]
@hlev Thanks for the investigation!
Good to know it's not a major issue.

**Comment by tfa2012** [comment]
> Everything is now in a zImage (Ramdisk) and everything just needs to be placed in the fat32 partition, the ext4 is used for cache.

Hello, can you tell me how to do that if I just have a empty 16GB sdcard? 
I searched the internet they wrote these:
```
// mount ...
sudo scripts/mkknlimg arch/arm/boot/zImage mnt/fat32/$KERNEL.img 
sudo cp arch/arm/boot/dts/*.dtb mnt/fat32/
sudo cp arch/arm/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
sudo cp arch/arm/boot/dts/overlays/README mnt/fat32/overlays/
sudo umount mnt/fat32
sudo umount mnt/ext4
```
But I stucked in the first step,
```
wpe-brmaster/output$ ls
build  host  images  mlmkmnt  n_zImage  staging  target
wpe-brmaster/output$ build/linux-be97febf4aa42b1d019ad24e7948739da8557f66/scripts/mkknlimg images/zImage n_zImage
* Is this a valid kernel?
DT: n
DDT: n
270x: n
283x: n
wpe-brmaster/output$
```
Even I continued to do subsequent steps and ran it in rpi3, I got the black screen, no anything displayed on hdmi.

Thank you.

**Comment by hlev** [comment]
@tfa2012 You only have to use the files in the `output/images` directory. 
Assuming that you have created the FAT and ext4 filesystems on the SD card already, then:
```
cd output/images
cp -r zImage  *.dtb ./rpi-firmware/* <path_to_the_FAT_mount>
```

This is just off the top of my head, there may be a couple more files intended for the FAT partition, maybe a config file for WPE, or similar. If you include a list of files in `/output/images`, I'll help you pick them. 
You will not need the intermediary image files, such as `rootfs.cpio`. That's used only for bundling the rootfs with the kernel.

Your FAT partition should look more or less like
```
bcm2710-rpi-3-b.dtb        <other .dtb files>         config.txt           start.elf
bootcode.bin         fixup.dat            zImage
cmdline.txt          overlays/
```
 
That's all. There's no need to touch the ext4 partition, the system will mount it at `/root` and use it for persistent data.

**Comment by SamDecrock** [comment]
@tfa2012 Just follow @T94T [post](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/500#issuecomment-435590466).

You'll get a nice sdcard.img

**Comment by tfa2012** [comment]
> @tfa2012 Just follow @T94T [post](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/500#issuecomment-435590466).
> 
> You'll get a nice sdcard.img

Thank you very much!
Maybe I do some wrong steps, it generates sdcard.img but doesn't work...
And follow @hlev 's suggestion,  finally it's ok. Thanks god.

Thank you two good man.

**Comment by tfa2012** [comment]
> @tfa2012 You only have to use the files in the `output/images` directory.
> Assuming that you have created the FAT and ext4 filesystems on the SD card already, then:
> 
> ```
> cd output/images
> cp -r zImage  *.dtb ./rpi-firmware/* <path_to_the_FAT_mount>
> ```
> This is just off the top of my head, there may be a couple more files intended for the FAT partition, maybe a config file for WPE, or similar. If you include a list of files in `/output/images`, I'll help you pick them.
> You will not need the intermediary image files, such as `rootfs.cpio`. That's used only for bundling the rootfs with the kernel.
> 
> Your FAT partition should look more or less like
> 
> ```
> bcm2710-rpi-3-b.dtb        <other .dtb files>         config.txt           start.elf
> bootcode.bin         fixup.dat            zImage
> cmdline.txt          overlays/
> ```
> That's all. There's no need to touch the ext4 partition, the system will mount it at `/root` and use it for persistent data.

Thanks a lot!
It is so simple, and it is really starting...

**Comment by tfa2012** [comment]
> @T94T I followed your instructions to generate the sdcard.img and it worked!
> It's showing me a nice "Hello" animation (which is suppose is WPE).
> 
> However, when I plug in a network cable, I get this:
> ![img_5231](https://user-images.githubusercontent.com/550487/48545303-e4d27800-e8c5-11e8-9a6e-c29dfd486d96.JPG)
> 
> Edit: despite the "something went wrong", I can go the the web interface running on the Pi and load the different test urls. This is cool :-)

When I see "We're ready!", then where to input address? I press keyboard but no any response.

**Comment by tfa2012** [comment]
@hlev @SamDecrock 
Sorry to disturb you, I have some questions:
1. What are default SSH2 username and password?
2. My screen show "Hello" or "We're ready" with black backgroud pages, but no control panel, where to input address?
3. Does this zImage surpport keyboard and mouse? I hit the keyboard but no response, mouse neither.

Thanks

![wc_20181130101347](https://user-images.githubusercontent.com/7530801/49264337-d15c0b00-f488-11e8-85c2-3e720af3b6b2.jpg)
![wc_20181130101354](https://user-images.githubusercontent.com/7530801/49264341-d6b95580-f488-11e8-930d-6c6ec378ad80.jpg)

**Comment by TOLDOTECHNIK** [comment]
You also can take our implementation from https://github.com/TOLDOTECHNIK/buildroot-webkit
It is well documented and will offer everything you need/requested including keyboard/mouse input.

(Our project is based on this great WebPlatformForEmbedded/buildroot repo.)

**Comment by hlev** [comment]
@tfa2012 

> What are default SSH2 username and password?

It is root/root and you can check and change the password in "System configuration" by running `make menuconfig`.

> My screen show "Hello" or "We're ready" with black backgroud pages, but no control panel, where to input address?

Don't expect a URL bar, because this is a full-screen (kiosk) browser implementation intended for embedded devices with limited user control, not a desktop browser. The URL the browser opens is controlled either by your configuration, or the remote control UI, on-the-fly. Visit `http://<your_device_IP>` and that should present you the remote control UI, if you use the native buildroot repo. (be aware, this does not work in the TOLDOTECHNIK project yet, if you decide to try it out)
 
> Does this zImage support keyboard and mouse? I hit the keyboard but no response, mouse neither.

You can check/change the kernel configuration with `make linux-menuconfig` prior to the build to enable/disable overall input device support. There is support for input in the browser itself.

I second @TOLDOTECHNIK, try out that build as well, which employs the current stable wpe-2017 and the older/simpler WPELauncher. It is somewhat easier to start with than the WPEFramework way.

**Comment by tfa2012** [comment]
@TOLDOTECHNIK Awesome! Your project is sure helpful to me. Thank you for your hard work!

@hlev It's very very kind of you, thanks again. Everything is OK. I should deeply study this project. 

So exciting!

**Comment by t3knomanzer** [comment]
@T94T I’m having the same issue:
Waiting for root device /dev/mmcblk0p2

Did you ever figure out what the problem was?

Thank you.

**Comment by T94T** [comment]
No, I haven't dealt with this problem since.

**Comment by t3knomanzer** [comment]
You mean it hasn’t happened again?
What changed?

It’s happening to me for the RAM disk version too. For that one I’m getting a mmcblk0p1 and p2 partitions not found.

**Comment by T94T** [comment]
I'm using this one instead: https://github.com/TOLDOTECHNIK/buildroot-webkit

**Comment by t3knomanzer** [comment]
:D 
I went the other way around. I got Toldotechnik working and now I wanted to get the source WPE working to implement my own customizations. 

Thank you. I guess I’ll have to keep digging.
