### ISSUE TITLE
rPi: GLES performance on dispmanx vs westeros/wayland

### ISSUE THREAD

**Issue by deeps8us** [WebPlatformForEmbedded/WPEWebKit#548]
Hello,

While developing our applications we ran into performance issues when running under wayland: the raspberry just seemed to be unable to keep up with our application, while it was running fine on Raspbian/X11. We replaced the wayland layer with dispmanx, and now performance is just as expected.
We lose portability with this though, as the dispmanx layer is not usable on other platforms.
The questions we have:
1. what causes the difference in performance between wayland and dispmanx. Is this the additional compositing step?
2. Is there a way to get native dispmanx performance on wayland so we can keep the wayland interface for portability?
3. Are there tools available for profiling GLES up to the driver level?

Thank you,

**Comment by jeffwannamaker** [comment]
Hi,
When using Westeros/Wayland on RPI, be sure to use the Westeros dispmanx render module rather than the gl render module:

westeros --renderer libwesteros_render_dispmanx.so.0.0.0 --display wayland-0

This should give good performance.  The issue with the gl render module is that the userland implementation of wayland-egl is only partial, and lacks the ability to call eglCreateImageKHR with wayland buffers.

The dispmanx render module is built from the sources in Westeros under the rpi/westeros-render-dispmanx folder and builds from its own recipe.

**Comment by deeps8us** [comment]
Thank you for the information
