### ISSUE TITLE
RPI: Remote web Inspector not working

### ISSUE THREAD

**Issue by deeps8us** [WebPlatformForEmbedded/WPEWebKit#549]
Trying to use remote web inspector in rpi. But getting error.

westeros --renderer libwesteros_render_gl.so.0.0.0 --framerate 60 --display main0 &
export WEBKIT_INSPECTOR_SERVER=${WEBKIT_INSPECTOR_SERVER:-':::9224'}
/usr/bin/WPELauncher  http://<ip>/wizardkit/ui/guide.html &

From browser: launch 
http://<board_ip>:9224/

Getting the error:
<h1>Inspectable web views</h1>
<p id="noPageNotice" style="color:grey">None found, make sure that you have set the developerExtrasEnabled preference property on your WebView.</p>

**Comment by aperezdc** [comment]
@deeps8us The `WEBKIT_INSPECTOR_SERVER` should have an valid address to bind to. Can you try setting it to `WEBKIT_INSPECTOR_SERVER=0.0.0.0:9224`? Also, if you are using a modern enought branch, you will need to access `inspector://<board-ip>:9224` from the browser instead of `http://<board-ip>:9224`. Also, you will need a WebKit-based browser like [GNOME Web](https://wiki.gnome.org/Apps/Web/) or [Midori](https://www.midori-browser.org).

**Comment by deeps8us** [comment]
Same issue after setting WEBKIT_INSPECTOR_SERVER=0.0.0.0:9224  and also with Midori

**Comment by aperezdc** [comment]
@deeps8us Which version of WPE WebKit are you using? It looks like you are using [WpeLauncher](https://github.com/WebPlatformForEmbedded/WPEWebKitLauncher). Is that so? Re-reading its code I see that it does not enable the developer extras, which is needed for the remote inspector to work — there is no call to `WKPreferencesSetDeveloperExtrasEnabled()`.

**Comment by albertd** [comment]
@deeps8us this enabled by default when using the wpeframework based startup, default set on port 9888

**Comment by Trinath402** [comment]
hi @aperezdc we enabled "WKPreferencesSetDeveloperExtrasEnabled" in our launcher code, but it didn't worked for us. We are still facing same error "None found, make sure that you have set the developerExtrasEnabled preference property on your WebView" on browser.

hi @albertd  we tried on 9888 port as well but still observes the same behaviour.

Is this WKPreferencesSetDeveloperExtrasEnabled needs to be enable from browser end?? (or) can we enable on platform directly.

**Comment by albertd** [comment]
@Trinath402 which build config are you using and are you using safari / chrome?

**Comment by hlev** [comment]
I'm running WPELauncher with the newer WPEWebkit (wpe-20170728), specifically: [371d4b0](https://github.com/WebPlatformForEmbedded/WPEWebKitLauncher/commit/371d4b0bcd96723d1d8383317c365f0935be3023) and c04a067fb08ad03f34f0ad1cfe2c95dc138cbdbb and I don't have an inspector either.

WPELauncher binds just fine to 9998, as `export WEBKIT_INSPECTOR_SERVER=0.0.0.0:9998` is set by the default `/usr/bin/wpe` script, but both over `http://` (Chromium/Midori) and `inspector://` (Midori) there's only an empty response I don't even see that error OP mentioned.

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9998            0.0.0.0:*               LISTEN      20424/WPELauncher
```

I have a warning when WPELauncher starts, but otherwise works fine, not sure if it's related.

```
** (process:19966): WARNING **: Error loading the injected bundle (/usr/lib/libWPEInjectedBundle.so): /usr/lib/libWPEInjectedBundle.so: undefined symbol: _ZN6WebKit22WebKitExtensionManager10initializeEPNS_14InjectedBundleEPN3API6ObjectE
[WPELauncher] Hello InjectedBundle ...
```
If I follow this thread correctly, I'll need the patch from @aperezdc and that should be it, or is there anything else I need to be aware of when "downgrading" to WPELauncher?

**Comment by albertd** [comment]
Please use the correct export:

https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins/blob/master/WebKitBrowser/WebKitImplementation.cpp#L743

**Comment by hlev** [comment]
Thanks, that works indeed.

**Comment by Trinath402** [comment]
Hi @albertd,
 
             I tried with enabling  WEBKIT_INSPECTOR_SERVER and  WEBKIT_LEGACY_INSPECTOR_SERVER with 9222 and 9998 ports. But i am getting raw data representation on my browser when i am accessing wpe-inspector page. I have used Google chrome and mozilla firefox as well for this.
Please see the error message in my attachment.

**Comment by Trinath402** [comment]
Hi @albertd,
 
             I tried with enabling  WEBKIT_INSPECTOR_SERVER and  WEBKIT_LEGACY_INSPECTOR_SERVER with 9222 and 9998 ports. But i am getting raw data representation on my browser when i am accessing wpe-inspector page. I have used Google chrome and mozilla firefox as well for this.
Please see the raw data in my attachment.
![chrome_response](https://user-images.githubusercontent.com/20659582/48906268-f0a3d880-ee89-11e8-9ffa-051838638022.png)


Could you please let us what we are missing here.

**Comment by aperezdc** [comment]
@Trinath402 It looks like the device where WPELauncher is running is missing the `shared-mime-info` package, which the inspector server uses (through GLib) to determine the `Content-Type` it has to return in its responses. Could you please try to add it to your build and try again?

**Comment by Trinath402** [comment]
Thank you @aperezdc  it's worked for me. After including this package in our image i am getting the response properly.
